### ISSUE TITLE
Sample form-validation index.php

### ISSUE THREAD

**Issue by kylefdyer** [Respect/samples#4]
Should it use NestedValidationExceptionInterface rather than ValidationException?

**Comment by henriquemoody** [comment]
Yes, it's better because of the [Interface segregation principle](http://en.wikipedia.org/wiki/Interface_segregation_principle).

I'm sorry, I totally forget about this project, Respect has a lot of little ones, @kylefdyer you can try a pull request if you want, it's gonna be awesome!

**Comment by henriquemoody** [comment]
I will close this since there is a long time since there is a long time since the last update, but feel free to open it any time.
